name: Docs

on: [push]

jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-python
      # ^-- This gives info on matrix testing.
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      # I don't know where the "run" thing is documented.
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y sphinx-build
          pip install -r docs/requirements.txt
      - name: Build Sphinx docs
        run: |
          sphinx-build -b html ./docs/ ./docs/_build/html
          make html