name: Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          apt-get update -qq && apt-get install -y -qq python3-sphinx
          pip3 install cython loguru coverage tqdm h5py sphinx-rtd-theme
          pip3 install word2vec torch torchvision
    - name: Docs building
      run: | 
          sphinx-build -b html ./docs/ ./docs/_build/html